### ISSUE TITLE
Calls to vignette 'Workflows'

### ISSUE THREAD

**Issue by beckerbenj** [kroehne/LogFSM#3]
Throughout the package documentation (e.g., help pages), calls to the vignette 'Workflows' are written as `vignette("Workflow", package = "LogFSM")`, but should probably be `vignette("Workflows", package = "LogFSM")`.

Maybe visibility for the vignettes could be increased in general by mentioning these in the ReadMe?

**Comment by kroehne** [comment]
Thank you. The typo was fixed. Making vignettes more visible in general has been postponed for the next major version.
